"""Email digest of the top new matches — built for a daily cron.

SMTP settings come from the environment (see .env.example):
    AUTOHAWK_SMTP_HOST / AUTOHAWK_SMTP_PORT (default 587)
    AUTOHAWK_SMTP_USER / AUTOHAWK_SMTP_PASSWORD
    AUTOHAWK_DIGEST_TO  (recipient)
    AUTOHAWK_DIGEST_FROM (defaults to AUTOHAWK_SMTP_USER)

With no SMTP host configured, the digest prints to stdout instead of
failing, so the command is always safe to run.
"""

from __future__ import annotations

import html
import os
import smtplib
import sqlite3
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

_HTML_SHELL = """<div style="font:15px/1.5 Georgia, serif; color:#1c1917; max-width:640px">
<h2 style="margin:0 0 4px">AutoHawk digest</h2>
<p style="color:#78716c; margin:0 0 20px">{count} new match{plural} worth a look</p>
{cards}
<p style="color:#78716c; font-size:13px">Generated by AutoHawk — run <code>autohawk shortlist</code> for the full ranking.</p>
</div>"""

_HTML_CARD = """<div style="border:1px solid #e7e5e4; border-radius:8px; padding:12px 16px; margin-bottom:12px">
<div><a href="{url}" style="color:#1c1917; font-weight:bold; text-decoration:none">{title}</a>
<span style="float:right; color:#b45309; font-weight:bold">{score}</span></div>
<div style="color:#78716c; font-size:13px">{company} &middot; {location} &middot; {recommendation}</div>
<p style="margin:8px 0 0; font-size:14px">{reasoning}</p>
</div>"""


def build_digest(rows: list[sqlite3.Row]) -> tuple[str, str, str]:
    """Return (subject, plain_text_body, html_body) for the given jobs."""
    count = len(rows)
    top = rows[0] if rows else None
    subject = (
        f"AutoHawk: {count} new match{'es' if count != 1 else ''}"
        + (f" — top: {top['title']} @ {top['company']} ({top['score']})" if top else "")
    )

    text_lines = [f"AutoHawk digest — {count} new match(es)\n"]
    cards = []
    for r in rows:
        text_lines.append(
            f"  [{r['score']}] {r['title']} @ {r['company']}"
            f" ({r['location'] or 'n/a'}) — {r['recommendation'] or 'unrated'}\n"
            f"        {r['url']}"
        )
        e = lambda key: html.escape(str(r[key] or ""))
        cards.append(
            _HTML_CARD.format(
                url=e("url"),
                title=e("title"),
                score=r["score"],
                company=e("company"),
                location=e("location") or "—",
                recommendation=e("recommendation") or "unrated",
                reasoning=e("reasoning"),
            )
        )
    html_body = _HTML_SHELL.format(
        count=count, plural="es" if count != 1 else "", cards="\n".join(cards)
    )
    return subject, "\n".join(text_lines), html_body


def smtp_configured() -> bool:
    return bool(os.environ.get("AUTOHAWK_SMTP_HOST") and os.environ.get("AUTOHAWK_DIGEST_TO"))


def send_email(subject: str, text_body: str, html_body: str) -> str:
    """Send the digest via SMTP. Returns the recipient address."""
    host = os.environ["AUTOHAWK_SMTP_HOST"]
    port = int(os.environ.get("AUTOHAWK_SMTP_PORT") or 587)
    user = os.environ.get("AUTOHAWK_SMTP_USER", "")
    password = os.environ.get("AUTOHAWK_SMTP_PASSWORD", "")
    to_addr = os.environ["AUTOHAWK_DIGEST_TO"]
    from_addr = os.environ.get("AUTOHAWK_DIGEST_FROM") or user or to_addr

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(text_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    if port == 465:
        server: smtplib.SMTP = smtplib.SMTP_SSL(host, port, timeout=30)
    else:
        server = smtplib.SMTP(host, port, timeout=30)
        server.starttls()
    try:
        if user:
            server.login(user, password)
        server.sendmail(from_addr, [to_addr], msg.as_string())
    finally:
        server.quit()
    return to_addr
